# create_groups.yml

---
- hosts: all
  become: yes
  tasks:
   - name: Ensure group "sas" exists
     group:
       name: sas
       state: present

   - name: Make sure we have a 'sasadmins' group
     group:
        name: sasadmins
        state: present